[package]
name = "aoclib"
version = "0.1.0"
authors = ["Lauri Koskela <lapamiko@gmail.com>"]
edition = "2021"


[dependencies]
regex = "1.5.4"
itertools = "0.12"
num-integer = "0.1.44"
ndarray = "0.15.4"
